In [1]:
import os
import dlib
import cv2
import time
import numpy as np
from PIL import Image
from scipy.spatial import distance as dist
from collections import OrderedDict
import tensorflow as tf


gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: 
    tf.config.experimental.set_memory_growth(gpu, True)


label_map= ["biscuit_a","biscuit_b","biscuit_c"]
label_map.sort()
detect_fn=tf.saved_model.load(".\\saved_model")

In [2]:
detect_fn

<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x116b50da788>

In [3]:
import math
from tensorflow.keras.applications import resnet50
from tensorflow.keras.layers import Dense, Conv2D, Flatten 
from tensorflow.keras import Model
from tensorflow.keras import layers
from tensorflow.keras.models import load_model
 
# load class model
class_model = load_model('.\\imageacc_model.h5')

#Backbone_SNN
# base_resnet=tf.keras.applications.ResNet50(include_top=False,weights="imagenet",input_shape=(150,150,3),classes=len(label_map))
# # for i in base_resnet.layers[:(math.ceil(len(base_resnet.layers)/2))]:
# #     i.trainable=False
# conv1=Conv2D(48,(1,1),padding="valid",activation="relu")
# dr1=layers.Dropout(0.3)
# avgpool1 = tf.keras.layers.AveragePooling2D(pool_size=(2, 2))
# conv2=Conv2D(78,(1,1),padding="same",activation="relu")
# dr2=layers.Dropout(0.2)
# flatten_layer = Flatten()
# dense1 = Dense(108,activation='sigmoid')

# embedding_model=tf.keras.Sequential([base_resnet,conv1,avgpool1,conv2,flatten_layer,dense1])
# embedding_model.load_weights(".\\checkpoint_94_0.00.hdf5")

In [4]:
class_model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_5 (Sequential)   (None, 108)               23723690  
                                                                 
 dense_9 (Dense)             (None, 3)                 327       
                                                                 
Total params: 23,724,017
Trainable params: 327
Non-trainable params: 23,723,690
_________________________________________________________________


In [5]:
def detect_boxes(frame, detect_fn,thresh,H,W):
        image_np = np.array(frame)
        input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.uint8)
        detections = detect_fn(input_tensor)
        # detection_classes should be ints.
        score_mask=(detections['detection_scores']>0.5).numpy().reshape(-1)
        rects_masked=detections['detection_boxes'].numpy().reshape(100,4)[score_mask]
        rects=(rects_masked*np.array([H,W,H,W])).astype(int)
        func=lambda x: (x[1]+x[3])/2
        rect_mask=np.array(list(map(func,rects)))>600*0.30
        print(rects)
        print(rect_mask)
        valid_rects=rects[rect_mask]
        print("Valid_rects\n {}".format(valid_rects))
        return valid_rects
    
def visualize_boxes(image,tracks):    
    for id_,track in tracks.items():
        (startY,startX,endY,endX) = track.box
        name="unknown" if track.name==None else track.name
        # draw the bounding box of the face along with the associated probability
        cv2.rectangle(image, (startX, startY), (endX, endY), (0, 0, 255), 2)
        cv2.putText(image, name, (startX, startY),cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2)
        #cv2.putText(image, name, (startX, startY),cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255,255), 2) 
    return image

In [6]:


# def get_name(model,svm,face_pixels,label_map):
#     img=cv2.resize(face_pixels,(160,160))
#     img = np.around(np.array(img) / 255.0, decimals=12)
#     x_train = np.expand_dims(img, axis=0)
#     embedding = model.predict(x_train)
#     embedding= embedding / np.linalg.norm(embedding, ord=2)
#     name=svm.predict(embedding.reshape(1,-1))
#     return label_map[name]



class Track():
    def __init__(self,tracker,box):
        self.tracker=tracker
        self.box=box
        self.recognized_face=False
        self.encodings=None 
        self.name=None
        self.prob_face={}
        self.centroid=self.get_centroid()
        self.rec_count=0
        #self.spoof_confirm=[]


    def update_track(self,frame):
        self.tracker.update(frame)
        pos=self.tracker.get_position()
        startX = int(pos.left())
        startY = int(pos.top())
        endX = int(pos.right())
        endY = int(pos.bottom())
        tracked_box=np.array([startY,startX,endY,endX])
        print("tracked_box")
        #print(("tracked_box",tracked_box))
        prev_box=np.array(self.box)
        #self.box=tracked_box.astype('int')
        return tracked_box
        #print(("prev_box",prev_box))
        #self.box=self.box if get_overlap(tracked_box,prev_box)>0.95 else tracked_box.astype('int')
        
    def box_recognize(self,image,class_model,label_map,tracker):
        global W,H
        if (self.name==None and 0.46*W<self.get_centroid()[1]<0.50*W):
            starty,startx,endy,endx=self.box
            box_roi = image[starty:endy,startx:endx]  
            img=cv2.cvtColor(box_roi,cv2.COLOR_BGR2RGB)
            im = Image.fromarray(img, 'RGB')
            #Resizing into dimensions you used
            im = im.resize((150,150))
            img_array = (np.array(im).astype(np.float32)/255)
            #Expand dimensions to match the 4 D Tensor shape.
            img_array = np.expand_dims(img_array, axis = 0)
            idx_=class_model.predict(img_array)
            name=label_map[np.argmax(idx_)]
            self.name=name
            tracker.count[name]=tracker.count.get(name,0)+1
            print(tracker.count)
    def get_box(self):
        pos=self.tracker.get_position()
        return [int(pos.left()),int(pos.top()),int(pos.right()),int(pos.bottom())]


    def get_centroid(self):
        box=self.box
        return (int((box[0]+box[2])/2),int((box[1]+box[3])/2))


class Tracker():
    
    global frame
    
    def __init__(self, maxDisappeared=5,maxDistance=150,thresh=None):
        # initialize the next unique object ID along with two ordered
        # dictionaries used to keep track of mapping a given object
        # ID to its centroid and number of consecutive frames it has
        # been marked as "disappeared", respectively
        self.nextObjectID = 0
        self.objects = OrderedDict()
        self.disappeared = OrderedDict()
        self.count={}
        self.thresh=thresh
        # store the number of maximum consecutive frames a given
        # object is allowed to be marked as "disappeared" until we
        # need to deregister the object from tracking
        self.maxDisappeared = maxDisappeared
        self.maxDistance=maxDistance

    def register(self, rect,frame):
    
        # when registering an object we use the next available object
        # ID to store the centroid
        t = dlib.correlation_tracker()
        (startY, startX, endY, endX)=rect
        drect = dlib.rectangle(startX, startY, endX, endY)
        t.start_track(frame, drect)
        name='obj_'+str(self.nextObjectID)
        self.objects[name] = Track(t,rect)
        self.disappeared[name] = 0
        self.nextObjectID+=1

    def deregister(self, objectID):
        # to deregister an object ID we delete the object ID from
        # both of our respective dictionaries
        trk=self.objects[objectID]
        startY,startX,endY,endX=trk.box
        print("vanishing_arr: {}".format(trk.box))
#         if int(startX/2+endX/2) <self.thresh:     
#             name=trk.name
#             self.count[name]=self.count.get(name,0)+1
        del self.objects[objectID]
        del self.disappeared[objectID]
        
    def deregister(self, objectID):
        # to deregister an object ID we delete the object ID from
        # both of our respective dictionaries
#         trk=self.objects[objectID]
#         startY,startX,endY,endX=trk.box
#         if int(startX/2+endX/2) <self.thresh:     
#             name=trk.name
#             self.count[name]=self.count.get(name,0)+1
            
        del self.objects[objectID]
        del self.disappeared[objectID]
        
    def track_update(self,frame):
        height,width,channel = frame.shape
        for objectID in list(self.disappeared.keys()):
            trk=self.objects[objectID]
            startY,startX,endY,endX=trk.box
            if int(startX/2+endX/2)<(0.35*width):
                self.disappeared[objectID]+=4.7
            if self.disappeared[objectID]>self.maxDisappeared:
                self.deregister(objectID)
        t_rects=[]
        for name in self.objects.keys():
            t_rect=self.objects[name].update_track(frame)
            t_rects.append(t_rect)
        return np.array(t_rects)


    def update(self,frame, coords,thresh):
        
        for objectID in list(self.disappeared.keys()):
            trk=self.objects[objectID]
            if trk.centroid[0]<thresh:
                self.disappeared[objectID]+=1.7
        
        
        
        if len(coords) == 0:
            # loop over any existing tracked objects and mark them
            # as disappeared
            for objectID in list(self.disappeared.keys()):
                self.disappeared[objectID] += 1

                # if we have reached a maximum number of consecutive
                # frames where a given object has been marked as
                # missing, deregister it
                if self.disappeared[objectID] > self.maxDisappeared:
                    self.deregister(objectID)

            # return early as there are no centroids or tracking info
            # to update
            return self.objects
        inputCentroids = np.zeros((len(coords), 2), dtype="int")

        # loop over the bounding box rectangles
        for (i, (startY, startX, endY, endX)) in enumerate(coords):
            # use the bounding box coordinates to derive the centroid
            cX = int((startX + endX) / 2.0)
            cY = int((startY + endY) / 2.0)
            inputCentroids[i] = (cX, cY)

        # initialize an array of input centroids for the current frame
        
        # if we are currently not tracking any objects take the input
        # centroids and register each of them

        if len(self.objects) == 0:
            for i in range(0, len(coords)):
                self.register(coords[i],frame)
            
            
        # otherwise, are are currently tracking objects so we need to
        # try to match the input centroids to existing object
        # centroids
        else:
            # grab the set of object IDs and corresponding centroids
            object_copy=self.objects.copy()
            tracks_copy=list(object_copy.values())
            #print('tracks:'+str(tracks_copy))
            objectIDs = list(object_copy.keys())
            #print('objectIDs:' + str(objectIDs))
            objectCentroids = [i.centroid for i in tracks_copy]

            # compute the distance between each pair of object
            # centroids and input centroids, respectively -- our
            # goal will be to match an input centroid to an existing
            # object centroid
            D = dist.cdist(np.array(objectCentroids), inputCentroids)

            # in order to perform this matching we must (1) find the
            # smallest value in each row and then (2) sort the row
            # indexes based on their minimum values so that the row
            # with the smallest value as at the *front* of the index
            # list
            rows = D.min(axis=1).argsort()
            # next, we perform a similar process on the columns by
            # finding the smallest value in each column and then
            # sorting using the previously computed row index list
            cols = D.argmin(axis=1)[rows]
            
            # in order to determine if we need to update, register,
            # or deregister an object we need to keep track of which
            # of the rows and column indexes we have already examined
            usedRows = set()
            usedCols = set()

            # loop over the combination of the (row, column) index
            # tuples
            for (row, col) in zip(rows, cols):
                # if we have already examined either the row or
                # column value before, ignore it
                # val
                if row in usedRows or col in usedCols:
                    continue
                # if the distance between centroids is greater than
                # the maximum distance, do not associate the two
                # centroids to the same object
                if D[row, col] > self.maxDistance:
                    continue

                # otherwise, grab the object ID for the current row,
                # set its new centroid, and reset the disappeared
                # counter
                objectID = objectIDs[row]
                prev_name=self.objects[objectID].name
                prev_recog_state=self.objects[objectID].recognized_face
                t = dlib.correlation_tracker()
                (y1,x1,y2,x2)=coords[col]
                #name=names[col]
                rect=coords[col]
                drect = dlib.rectangle(int(x1),int(y1),int(x2),int(y2))
                t.start_track(frame, drect)
                n_track=Track(t,rect)
                self.objects[objectID] = n_track
                self.objects[objectID].name=prev_name
                self.objects[objectID].recognized_face=prev_recog_state
                #self.objects[objectID].box = coords[col]
                self.disappeared[objectID] = 0

                # indicate that we have examined each of the row and
                # column indexes, respectively
                usedRows.add(row)
                usedCols.add(col)

            # compute both the row and column index we have NOT yet
            # examined
            unusedRows = set(range(0, D.shape[0])).difference(usedRows)
            unusedCols = set(range(0, D.shape[1])).difference(usedCols)

            # in the event that the number of object centroids is
            # equal or greater than the number of input centroids
            # we need to check and see if some of these objects have
            # potentially disappeared
            if D.shape[0] >= D.shape[1]:
                # loop over the unused row indexes
                for row in unusedRows:
                    # grab the object ID for the corresponding row
                    # index and increment the disappeared counter
                    objectID = objectIDs[row]
                    self.disappeared[objectID] += 1

                    # check to see if the number of consecutive
                    # frames the object has been marked "disappeared"
                    # for warrants deregistering the object
                    if self.disappeared[objectID] > self.maxDisappeared:
                        self.deregister(objectID)

            # otherwise, if the number of input centroids is greater
            # than the number of existing object centroids we need to
            # register each new input centroid as a trackable object
            else:
                for col in unusedCols:
                    self.register(coords[col],frame)

        # return the set of trackable objects
        return self.objects


In [8]:
import imutils
import time
from PIL import Image
cap=cv2.VideoCapture(".\\testing_videos\\short_6.mp4")
#if vid_path:
    #cap=cv2.VideoCapture(r'G:\Wondershare UniConverter\Converted\ch01_20210707001338.mp4')
#else:

fps = cap.get(cv2.CAP_PROP_FPS)
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#out = cv2.VideoWriter('full_output.avi',cv2.VideoWriter_fourcc('M','J','P','G'), fps, (W,H))
fc=0
thresh=int(600*0.30)
tic=time.time()
name_thresh=600*0.50
tracker=Tracker(maxDisappeared=2,maxDistance=150,thresh=thresh)
func=lambda x: (x[1]+x[3])/2
FPS=[]
while True:
    ret, frame = cap.read()
    if not ret:
        break
    start=time.time()
    img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    im = Image.fromarray(img, 'RGB')
            #Resizing into dimensions you used
    im = im.resize((337,600))
    img_array = (np.array(im).astype(np.float32))
            #Expand dimensions to match the 4 D Tensor shape.
    
    frame=imutils.resize(frame, width=600)
    H,W=frame.shape[:2]
    print("height: {}, width: {}".format(H,W))
    if (fc==0 or fc%4==0):
        rects=detect_boxes(img_array, detect_fn,thresh,H,W)
#         rect_mask=np.array(list(map(func,rects)))>thresh
#         print(rects)
#         print(rect_mask)
#         valid_rects=rects[rect_mask]
        tracker.objects=tracker.update(frame,rects,thresh)
       
    else:
        t_rects=tracker.track_update(frame)
#         rect_mask=np.array(list(map(func,t_rects)))>thresh
#         print(rects)
#         print(rect_mask)
#         valid_rects=t_rects[rect_mask]  
#         print("tracked_valids: \n {}".format(valid_rects))
        tracker.objects=tracker.update(frame,t_rects,thresh)
            
    #Performing Liveness test for antispoofing and 
    #implementing face recognition per face tracked
    for i in tracker.objects.values():
        i.box_recognize(frame,class_model,label_map,tracker)
    image=visualize_boxes(frame,tracker.objects)
    y_stat=20
    for item,count in tracker.count.items():
        cv2.putText(image,'{}: {}'.format(item,count),(0,y_stat),cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)
        y_stat+=20
    blk = np.zeros(image.shape, np.uint8)
    cv2.rectangle(blk, (int(0.45*W),0), (int(0.55*W), 337), (0, 255, 0), -1)
    res = cv2.addWeighted(image,1, blk, 0.25, 1)

    # Putting the image back to its position
    res=imutils.resize(res,width=1200)
    cv2.imshow('faces',res)
    fc+=1
    end=time.time()
    print("FPS: {}".format(1/(end-start)))
    FPS.append(int(1/(end-start)))
    print(tracker.objects.keys())
    if cv2.waitKey(10) & 0xff==ord('q'):
        print("STOPPING APPLICATION")
        
        break
print("MEAN FPS THROUGHOUT VIDEO: {}".format(np.array(FPS).sum()/len(FPS)))        
cap.release()
cv2.destroyAllWindows()

height: 337, width: 600
[[122 464 244 592]
 [ 98 492 135 600]]
[ True  True]
Valid_rects
 [[122 464 244 592]
 [ 98 492 135 600]]
FPS: 0.11244157027614227
odict_keys(['obj_0', 'obj_1'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 10.243701337397301
odict_keys(['obj_0'])
height: 337, width: 600
tracked_box
FPS: 12.374731885490394
odict_keys(['obj_0'])
height: 337, width: 600
tracked_box
FPS: 15.213952003714343
odict_keys([])
height: 337, width: 600
[[130 450 252 585]]
[ True]
Valid_rects
 [[130 450 252 585]]
FPS: 8.757491037480765
odict_keys(['obj_2'])
height: 337, width: 600
tracked_box
FPS: 14.532774332143724
odict_keys(['obj_2'])
height: 337, width: 600
tracked_box
FPS: 12.911549673848466
odict_keys(['obj_2'])
height: 337, width: 600
tracked_box
FPS: 14.324710896783492
odict_keys([])
height: 337, width: 600
[[140 430 260 578]]
[ True]
Valid_rects
 [[140 430 260 578]]
FPS: 8.49493055077348
odict_keys(['obj_3'])
height: 337, width: 600
tracked_box
FPS: 14.12190285077456
odict_k

height: 337, width: 600
[[181   7 267 122]]
[False]
Valid_rects
 []
FPS: 9.37327001508464
odict_keys([])
height: 337, width: 600
FPS: 18.240545524127615
odict_keys([])
height: 337, width: 600
FPS: 18.230238966593358
odict_keys([])
height: 337, width: 600
FPS: 20.053567928091606
odict_keys([])
height: 337, width: 600
[[176   3 257 108]
 [238   0 278  85]]
[False False]
Valid_rects
 []
FPS: 10.34009392680612
odict_keys([])
height: 337, width: 600
FPS: 18.918315246317196
odict_keys([])
height: 337, width: 600
FPS: 18.23103136518534
odict_keys([])
height: 337, width: 600
FPS: 17.90509365981934
odict_keys([])
height: 337, width: 600
[[170   0 251 101]
 [229   0 269  71]]
[False False]
Valid_rects
 []
FPS: 9.82988546693259
odict_keys([])
height: 337, width: 600
FPS: 20.46261477065384
odict_keys([])
height: 337, width: 600
FPS: 19.671065837483937
odict_keys([])
height: 337, width: 600
FPS: 17.451761484914933
odict_keys([])
height: 337, width: 600
[[165   0 236  96]]
[False]
Valid_rects
 []
FP

FPS: 15.915850187834403
odict_keys(['obj_37'])
height: 337, width: 600
tracked_box
FPS: 16.17211995959191
odict_keys([])
height: 337, width: 600
[[128 311 305 509]]
[ True]
Valid_rects
 [[128 311 305 509]]
FPS: 8.952413070344132
odict_keys(['obj_38'])
height: 337, width: 600
tracked_box
FPS: 15.923584483033538
odict_keys(['obj_38'])
height: 337, width: 600
tracked_box
FPS: 16.43716395215776
odict_keys(['obj_38'])
height: 337, width: 600
tracked_box
FPS: 15.198570843615359
odict_keys([])
height: 337, width: 600
[[135 275 322 492]
 [171 454 277 534]]
[ True  True]
Valid_rects
 [[135 275 322 492]
 [171 454 277 534]]
FPS: 8.604194702464962
odict_keys(['obj_39', 'obj_40'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.5547612738096
odict_keys(['obj_39', 'obj_40'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.285776566757493
odict_keys(['obj_39', 'obj_40'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.531465236491636
odict_keys([])
height: 337, width: 600
[[14

tracked_box
FPS: 16.279581745212347
odict_keys(['obj_55'])
height: 337, width: 600
tracked_box
FPS: 15.198405623799689
odict_keys([])
height: 337, width: 600
[[137 458 251 574]
 [192  29 248 111]]
[ True False]
Valid_rects
 [[137 458 251 574]]
FPS: 8.873228233183553
odict_keys(['obj_56'])
height: 337, width: 600
tracked_box
FPS: 17.599536755357317
odict_keys(['obj_56'])
height: 337, width: 600
tracked_box
FPS: 15.419555019631487
odict_keys(['obj_56'])
height: 337, width: 600
tracked_box
FPS: 15.67401605405163
odict_keys([])
height: 337, width: 600
[[143 442 265 572]
 [189  34 241 105]]
[ True False]
Valid_rects
 [[143 442 265 572]]
FPS: 9.201203045785501
odict_keys(['obj_57'])
height: 337, width: 600
tracked_box
FPS: 16.44515542172454
odict_keys(['obj_57'])
height: 337, width: 600
tracked_box
FPS: 15.915970978415956
odict_keys(['obj_57'])
height: 337, width: 600
tracked_box
FPS: 16.029656919884278
odict_keys([])
height: 337, width: 600
[[155 423 280 567]]
[ True]
Valid_rects
 [[155 423

FPS: 14.744741809949343
odict_keys(['obj_79'])
height: 337, width: 600
tracked_box
FPS: 15.666756312565367
odict_keys([])
height: 337, width: 600
[[175 445 248 560]
 [191   6 267 121]
 [ 74 466 193 549]]
[ True False  True]
Valid_rects
 [[175 445 248 560]
 [ 74 466 193 549]]
FPS: 8.220692142301353
odict_keys(['obj_81', 'obj_82'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.122093042831217
odict_keys(['obj_81'])
height: 337, width: 600
tracked_box
FPS: 13.735783806442317
odict_keys(['obj_81'])
height: 337, width: 600
tracked_box
FPS: 15.26022732234075
odict_keys([])
height: 337, width: 600
[[ 78 449 205 544]
 [184 422 265 554]
 [188  12 259 117]]
[ True  True False]
Valid_rects
 [[ 78 449 205 544]
 [184 422 265 554]]
FPS: 8.520782376219923
odict_keys(['obj_83', 'obj_84'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.74526016783207
odict_keys(['obj_84'])
height: 337, width: 600
tracked_box
FPS: 15.273452919370461
odict_keys(['obj_84'])
height: 337, width: 600
track

FPS: 20.053567928091606
odict_keys([])
height: 337, width: 600
FPS: 17.276293568610004
odict_keys([])
height: 337, width: 600
[[204  17 261 107]
 [119  30 216  87]]
[False False]
Valid_rects
 []
FPS: 10.026879843941995
odict_keys([])
height: 337, width: 600
FPS: 20.449545354818262
odict_keys([])
height: 337, width: 600
FPS: 17.468187629887844
odict_keys([])
height: 337, width: 600
FPS: 17.287401801980035
odict_keys([])
height: 337, width: 600
[[200  13 249 102]
 [116  30 211  84]]
[False False]
Valid_rects
 []
FPS: 10.131120139516234
odict_keys([])
height: 337, width: 600
FPS: 18.567247164649533
odict_keys([])
height: 337, width: 600
FPS: 19.282028649712217
odict_keys([])
height: 337, width: 600
FPS: 20.064984021890965
odict_keys([])
height: 337, width: 600
[[195  16 240  98]
 [117  32 207  88]]
[False False]
Valid_rects
 []
FPS: 9.459072293286665
odict_keys([])
height: 337, width: 600
FPS: 16.17211995959191
odict_keys([])
height: 337, width: 600
FPS: 18.567904732391874
odict_keys([])


tracked_box
{'ep_green': 5, 'ep_black': 4}
FPS: 7.192076600181075
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 13.193161694163534
odict_keys(['obj_115'])
height: 337, width: 600
[[201 184 310 389]]
[ True]
Valid_rects
 [[201 184 310 389]]
FPS: 9.701828039813009
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 14.3245641297109
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 13.926468000332033
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 14.329702767338572
odict_keys(['obj_115'])
height: 337, width: 600
[[203 154 311 363]]
[ True]
Valid_rects
 [[203 154 311 363]]
FPS: 8.797756462022834
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 14.122711202397387
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 13.734569376815344
odict_keys(['obj_115'])
height: 337, width: 600
tracked_box
FPS: 12.696507653980161
odict_keys(['obj_115'])
height: 337, width: 600
[[202 132 315 337]]
[ True]
Valid_re

height: 337, width: 600
FPS: 17.287045547280393
odict_keys([])
height: 337, width: 600
[[ 70 494 190 545]]
[ True]
Valid_rects
 [[ 70 494 190 545]]
FPS: 9.665987592297268
odict_keys(['obj_124'])
height: 337, width: 600
tracked_box
FPS: 13.524036151765188
odict_keys([])
height: 337, width: 600
FPS: 18.92838962398686
odict_keys([])
height: 337, width: 600
FPS: 15.192019877864144
odict_keys([])
height: 337, width: 600
[[ 84 487 204 540]]
[ True]
Valid_rects
 [[ 84 487 204 540]]
FPS: 9.318107899156677
odict_keys(['obj_125'])
height: 337, width: 600
tracked_box
FPS: 14.531565927783976
odict_keys([])
height: 337, width: 600
FPS: 17.871144496947128
odict_keys([])
height: 337, width: 600
FPS: 17.599241365709563
odict_keys([])
height: 337, width: 600
[[ 83 480 217 540]]
[ True]
Valid_rects
 [[ 83 480 217 540]]
FPS: 8.873059291179837
odict_keys(['obj_126'])
height: 337, width: 600
tracked_box
FPS: 15.425566188315079
odict_keys([])
height: 337, width: 600
FPS: 20.054526763728514
odict_keys([])
he

[[162  42 296 182]
 [169 377 277 523]]
[False  True]
Valid_rects
 [[169 377 277 523]]
FPS: 9.737392685180456
odict_keys(['obj_154'])
height: 337, width: 600
tracked_box
FPS: 14.852088312883978
odict_keys(['obj_154'])
height: 337, width: 600
tracked_box
FPS: 15.395670143961473
odict_keys(['obj_154'])
height: 337, width: 600
tracked_box
FPS: 15.425906583302686
odict_keys([])
height: 337, width: 600
[[158  37 290 159]
 [183 355 286 501]
 [ 41 421 105 497]]
[False  True  True]
Valid_rects
 [[183 355 286 501]
 [ 41 421 105 497]]
FPS: 8.700016386539806
odict_keys(['obj_155', 'obj_156'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 12.425358454793223
odict_keys(['obj_155'])
height: 337, width: 600
tracked_box
FPS: 16.437357202481493
odict_keys(['obj_155'])
height: 337, width: 600
tracked_box
FPS: 14.32936007680035
odict_keys([])
height: 337, width: 600
[[192 330 300 486]
 [158  34 282 139]
 [ 45 428 113 504]]
[ True False  True]
Valid_rects
 [[192 330 300 486]
 [ 45 428 113 504]]
FPS:

[[143 332 290 489]
 [114 108 182 167]
 [185  36 241 111]
 [142 469 267 556]]
[ True False False  True]
Valid_rects
 [[143 332 290 489]
 [142 469 267 556]]
FPS: 8.79250029348136
odict_keys(['obj_180', 'obj_181'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.735378972704796
odict_keys(['obj_180', 'obj_181'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.280636816424494
odict_keys(['obj_180', 'obj_181'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.92720788686375
odict_keys([])
height: 337, width: 600
[[153 444 280 551]
 [149 297 303 462]
 [110 115 178 171]
 [183  36 234 109]]
[ True  True False False]
Valid_rects
 [[153 444 280 551]
 [149 297 303 462]]
FPS: 8.881476666109055
odict_keys(['obj_182', 'obj_183'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.33063301000065
odict_keys(['obj_182', 'obj_183'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.549462938734635
odict_keys(['obj_182', 'obj_183'])
height: 337, width: 600
tracked_box
tr

height: 337, width: 600
FPS: 12.608191423804728
odict_keys([])
height: 337, width: 600
FPS: 15.915427435236797
odict_keys([])
height: 337, width: 600
[[125 427 236 556]
 [194  12 265 135]
 [149  34 201 113]]
[ True False False]
Valid_rects
 [[125 427 236 556]]
FPS: 0.00010732179782891467
odict_keys(['obj_201'])
height: 337, width: 600
tracked_box
FPS: 3.298248925040655
odict_keys(['obj_201'])
height: 337, width: 600
tracked_box
FPS: 6.113833842296676
odict_keys(['obj_201'])
height: 337, width: 600
tracked_box
FPS: 6.640160720137669
odict_keys([])
height: 337, width: 600
[[135 416 246 555]
 [191  22 259 127]]
[ True False]
Valid_rects
 [[135 416 246 555]]
FPS: 7.135900642252563
odict_keys(['obj_202'])
height: 337, width: 600
tracked_box
FPS: 11.936457343206616
odict_keys(['obj_202'])
height: 337, width: 600
tracked_box
FPS: 11.394035543337118
odict_keys(['obj_202'])
height: 337, width: 600
tracked_box
FPS: 12.080333870006134
odict_keys([])
height: 337, width: 600
[[141 394 259 549]
 [18

FPS: 25.710632298403162
odict_keys([])
height: 337, width: 600
[[ 86 453 164 551]
 [187  29 250 132]]
[ True False]
Valid_rects
 [[ 86 453 164 551]]
FPS: 13.193244692730401
odict_keys(['obj_215'])
height: 337, width: 600
tracked_box
FPS: 22.29755563352578
odict_keys([])
height: 337, width: 600
FPS: 25.709844305504475
odict_keys([])
height: 337, width: 600
FPS: 23.874953039082868
odict_keys([])
height: 337, width: 600
[[ 92 456 177 553]
 [185  31 245 124]]
[ True False]
Valid_rects
 [[ 92 456 177 553]]
FPS: 12.69719949263319
odict_keys(['obj_216'])
height: 337, width: 600
tracked_box
FPS: 22.28168295792605
odict_keys([])
height: 337, width: 600
FPS: 25.068008630324474
odict_keys([])
height: 337, width: 600
FPS: 26.40800367695669
odict_keys([])
height: 337, width: 600
[[100 457 188 554]
 [180  30 240 125]]
[ True False]
Valid_rects
 [[100 457 188 554]]
FPS: 13.550119532209084
odict_keys(['obj_217'])
height: 337, width: 600
tracked_box
FPS: 21.809892258413413
odict_keys([])
height: 337, w

FPS: 25.729242962390426
odict_keys([])
height: 337, width: 600
FPS: 26.385908404630097
odict_keys([])
height: 337, width: 600
[[208  63 312 247]
 [119 472 197 568]]
[False  True]
Valid_rects
 [[119 472 197 568]]
FPS: 13.19299570016262
odict_keys(['obj_241'])
height: 337, width: 600
tracked_box
FPS: 22.28274832519617
odict_keys([])
height: 337, width: 600
FPS: 26.40950018259895
odict_keys([])
height: 337, width: 600
FPS: 24.45430163949719
odict_keys([])
height: 337, width: 600
[[206  46 310 218]
 [125 468 207 564]]
[False  True]
Valid_rects
 [[125 468 207 564]]
FPS: 12.922807687804637
odict_keys(['obj_242'])
height: 337, width: 600
tracked_box
FPS: 21.796744756480347
odict_keys([])
height: 337, width: 600
FPS: 26.40866876963664
odict_keys([])
height: 337, width: 600
FPS: 25.73429456698469
odict_keys([])
height: 337, width: 600
[[203  35 301 196]
 [134 466 221 559]]
[False  True]
Valid_rects
 [[134 466 221 559]]
FPS: 13.027002515762337
odict_keys(['obj_243'])
height: 337, width: 600
trac

[[ 93 437 230 549]
 [207  30 293 157]]
[ True False]
Valid_rects
 [[ 93 437 230 549]]
FPS: 12.692242981038667
odict_keys(['obj_265'])
height: 337, width: 600
tracked_box
FPS: 21.334201424211596
odict_keys([])
height: 337, width: 600
FPS: 24.4554423117289
odict_keys([])
height: 337, width: 600
FPS: 25.68921608858891
odict_keys([])
height: 337, width: 600
[[102 425 248 543]
 [199  23 285 149]]
[ True False]
Valid_rects
 [[102 425 248 543]]
FPS: 13.19851724116229
odict_keys(['obj_266'])
height: 337, width: 600
tracked_box
FPS: 21.797764254049756
odict_keys([])
height: 337, width: 600
FPS: 25.70937153294962
odict_keys([])
height: 337, width: 600
FPS: 26.388398502626696
odict_keys([])
height: 337, width: 600
[[114 407 269 530]
 [192  21 274 136]]
[ True False]
Valid_rects
 [[114 407 269 530]]
FPS: 12.53295563882365
odict_keys(['obj_267'])
height: 337, width: 600
tracked_box
FPS: 21.334201424211596
odict_keys(['obj_267'])
height: 337, width: 600
tracked_box
FPS: 21.812274105392348
odict_keys

height: 337, width: 600
[[218 125 324 272]
 [164 365 293 538]
 [179  28 284 191]]
[ True  True False]
Valid_rects
 [[218 125 324 272]
 [164 365 293 538]]
FPS: 11.796033962465794
odict_keys(['obj_288', 'obj_295'])
height: 337, width: 600
tracked_box
FPS: 20.942514617255103
odict_keys(['obj_295'])
height: 337, width: 600
tracked_box
FPS: 20.889632640051
odict_keys(['obj_295'])
height: 337, width: 600
tracked_box
FPS: 21.79765097183245
odict_keys([])
height: 337, width: 600
[[217 100 321 243]
 [169 335 310 525]
 [184  28 272 174]
 [ 57 421 120 491]]
[False  True False  True]
Valid_rects
 [[169 335 310 525]
 [ 57 421 120 491]]
FPS: 11.266106894013872
odict_keys(['obj_296', 'obj_297'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.918485909140117
odict_keys(['obj_296'])
height: 337, width: 600
tracked_box
FPS: 20.889320523739087
odict_keys(['obj_296'])
height: 337, width: 600
tracked_box
FPS: 20.889320523739087
odict_keys([])
height: 337, width: 600
[[181 308 322 510]
 [218  82 31

FPS: 21.797764254049756
odict_keys([])
height: 337, width: 600
[[186 324 295 463]
 [184  25 246 119]]
[ True False]
Valid_rects
 [[186 324 295 463]]
FPS: 13.198226518519917
odict_keys(['obj_318'])
height: 337, width: 600
tracked_box
FPS: 22.282156441913344
odict_keys(['obj_318'])
height: 337, width: 600
tracked_box
FPS: 21.81476993171026
odict_keys(['obj_318'])
height: 337, width: 600
tracked_box
FPS: 21.318911665590804
odict_keys([])
height: 337, width: 600
[[189 289 305 443]
 [180  32 236 113]]
[ True False]
Valid_rects
 [[189 289 305 443]]
FPS: 12.692127759369374
odict_keys(['obj_319'])
height: 337, width: 600
tracked_box
FPS: 21.809211826246113
odict_keys(['obj_319'])
height: 337, width: 600
tracked_box
FPS: 21.79663148485935
odict_keys(['obj_319'])
height: 337, width: 600
tracked_box
FPS: 18.568069131605043
odict_keys(['obj_319'])
height: 337, width: 600
[[194 264 311 419]
 [178  33 231 112]]
[ True False]
Valid_rects
 [[194 264 311 419]]
FPS: 13.192829710338668
odict_keys(['obj_3

FPS: 18.91763262581524
odict_keys([])
height: 337, width: 600
FPS: 25.709844305504475
odict_keys([])
height: 337, width: 600
FPS: 27.852658560718247
odict_keys([])
height: 337, width: 600
[[ 95 480 198 571]
 [ 92 449 132 487]]
[ True  True]
Valid_rects
 [[ 95 480 198 571]
 [ 92 449 132 487]]
FPS: 11.936559253008825
odict_keys(['obj_340', 'obj_341'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.57769155471695
odict_keys([])
height: 337, width: 600
FPS: 26.40800367695669
odict_keys([])
height: 337, width: 600
FPS: 25.70921394596185
odict_keys([])
height: 337, width: 600
[[104 474 211 568]
 [ 96 454 134 490]]
[ True  True]
Valid_rects
 [[104 474 211 568]
 [ 96 454 134 490]]
FPS: 11.269799984953194
odict_keys(['obj_342', 'obj_343'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.928645892095584
odict_keys([])
height: 337, width: 600
FPS: 25.70937153294962
odict_keys([])
height: 337, width: 600
FPS: 25.46431672059886
odict_keys([])
height: 337, width: 600
[[108 460 231 5

[[223  86 320 293]
 [170  30 281 149]
 [ 86 453 145 539]]
[ True False  True]
Valid_rects
 [[223  86 320 293]
 [ 86 453 145 539]]
FPS: 11.936525282881407
odict_keys(['obj_365', 'obj_366'])
height: 337, width: 600
tracked_box
FPS: 21.332248319075568
odict_keys([])
height: 337, width: 600
FPS: 25.7096867127209
odict_keys([])
height: 337, width: 600
FPS: 25.70937153294962
odict_keys([])
height: 337, width: 600
[[223  53 312 262]
 [168  23 275 134]
 [ 93 457 154 547]]
[False False  True]
Valid_rects
 [[ 93 457 154 547]]
FPS: 13.19909872487192
odict_keys(['obj_367'])
height: 337, width: 600
tracked_box
FPS: 22.281801327036373
odict_keys([])
height: 337, width: 600
FPS: 26.386074396542504
odict_keys([])
height: 337, width: 600
FPS: 26.361530290936287
odict_keys([])
height: 337, width: 600
[[218  44 311 226]
 [164  15 263 120]
 [ 99 461 163 553]]
[False False  True]
Valid_rects
 [[ 99 461 163 553]]
FPS: 12.85468576647481
odict_keys(['obj_368'])
height: 337, width: 600
tracked_box
FPS: 21.7976

FPS: 19.661015042352027
odict_keys(['obj_382'])
height: 337, width: 600
tracked_box
FPS: 18.92821878243603
odict_keys(['obj_382'])
height: 337, width: 600
[[219 133 316 273]
 [ 56 464 132 536]]
[ True  True]
Valid_rects
 [[219 133 316 273]
 [ 56 464 132 536]]
FPS: 11.270254220664935
odict_keys(['obj_382', 'obj_389'])
height: 337, width: 600
tracked_box
FPS: 22.280736050316605
odict_keys([])
height: 337, width: 600
FPS: 26.404678715997154
odict_keys([])
height: 337, width: 600
FPS: 26.386240390543414
odict_keys([])
height: 337, width: 600
[[223 108 313 236]
 [ 62 468 140 550]]
[False  True]
Valid_rects
 [[ 62 468 140 550]]
FPS: 12.533704675444206
odict_keys(['obj_390'])
height: 337, width: 600
tracked_box
FPS: 21.797197854737455
odict_keys([])
height: 337, width: 600
FPS: 27.0755724254572
odict_keys([])
height: 337, width: 600
FPS: 25.068308280787736
odict_keys([])
height: 337, width: 600
[[217  81 307 211]
 [ 67 474 149 555]]
[False  True]
Valid_rects
 [[ 67 474 149 555]]
FPS: 13.02142

FPS: 14.531314202169492
odict_keys(['obj_412', 'obj_416'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 15.916091770830961
odict_keys(['obj_412', 'obj_416'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.180042973918614
odict_keys(['obj_412'])
height: 337, width: 600
[[170 167 332 306]
 [205 298 330 500]
 [ 71 441 142 533]]
[ True  True  True]
Valid_rects
 [[170 167 332 306]
 [205 298 330 500]
 [ 71 441 142 533]]
FPS: 11.113241392101532
odict_keys(['obj_412', 'obj_418', 'obj_419'])
height: 337, width: 600
tracked_box
tracked_box
tracked_box
FPS: 14.965706966006687
odict_keys(['obj_412', 'obj_418'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.43787255889419
odict_keys(['obj_412', 'obj_418'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.7117061120408
odict_keys(['obj_412'])
height: 337, width: 600
[[177 141 331 266]
 [213 257 330 467]
 [ 77 447 148 543]]
[ True  True  True]
Valid_rects
 [[177 141 331 266]
 [213 257 330 467]
 [ 77 447 148 543]]
FPS

{'ep_green': 12, 'ep_black': 14}
FPS: 9.373081495651242
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 19.294801729689944
odict_keys(['obj_438'])
height: 337, width: 600
[[207 172 320 382]
 [175  20 228 112]
 [143  60 192 138]]
[ True False False]
Valid_rects
 [[207 172 320 382]]
FPS: 13.025829272761717
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 18.91814458657333
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 16.179106780537104
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 18.578596739900778
odict_keys(['obj_438'])
height: 337, width: 600
[[210 141 321 347]
 [170  27 224 120]
 [142  69 189 143]]
[ True False False]
Valid_rects
 [[210 141 321 347]]
FPS: 12.855000950110028
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 19.282383229128357
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 18.9190832532691
odict_keys(['obj_438'])
height: 337, width: 600
tracked_box
FPS: 18.918485909

height: 337, width: 600
tracked_box
tracked_box
FPS: 19.6601856191994
odict_keys([])
height: 337, width: 600
FPS: 26.406174844810437
odict_keys([])
height: 337, width: 600
FPS: 25.70937153294962
odict_keys([])
height: 337, width: 600
[[ 48 398 105 473]
 [ 40 448 126 537]]
[ True  True]
Valid_rects
 [[ 48 398 105 473]
 [ 40 448 126 537]]
FPS: 12.08047304556203
odict_keys(['obj_445', 'obj_446'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.92787710858597
odict_keys([])
height: 337, width: 600
FPS: 25.72687570538299
odict_keys([])
height: 337, width: 600
FPS: 25.70921394596185
odict_keys([])
height: 337, width: 600
[[ 44 456 138 548]
 [ 50 402 107 481]]
[ True  True]
Valid_rects
 [[ 44 456 138 548]
 [ 50 402 107 481]]
FPS: 11.018359975306371
odict_keys(['obj_447', 'obj_448'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.918315246317196
odict_keys([])
height: 337, width: 600
FPS: 25.08374997009784
odict_keys([])
height: 337, width: 600
FPS: 24.470280740239435
odict_ke

height: 337, width: 600
tracked_box
tracked_box
FPS: 15.425849849761494
odict_keys(['obj_472', 'obj_474'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 15.915548219401597
odict_keys(['obj_472', 'obj_474'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 15.341553430018838
odict_keys(['obj_472'])
height: 337, width: 600
[[167 125 330 340]
 [189 305 325 481]]
[ True  True]
Valid_rects
 [[167 125 330 340]
 [189 305 325 481]]
FPS: 11.941520967324058
odict_keys(['obj_472', 'obj_475'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.711373189632848
odict_keys(['obj_472', 'obj_475'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.179169190058673
odict_keys(['obj_472', 'obj_475'])
height: 337, width: 600
tracked_box
FPS: 20.463513282755592
odict_keys([])
height: 337, width: 600
[[173 100 323 296]
 [200 260 328 460]]
[ True  True]
Valid_rects
 [[173 100 323 296]
 [200 260 328 460]]
FPS: 12.08036866359447
odict_keys(['obj_476', 'obj_477'])
height: 337, width: 600
tr

FPS: 12.080507839952073
odict_keys(['obj_501', 'obj_502'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.230555917764157
odict_keys(['obj_501'])
height: 337, width: 600
tracked_box
FPS: 21.333333333333332
odict_keys(['obj_501'])
height: 337, width: 600
tracked_box
FPS: 20.053280295279166
odict_keys([])
height: 337, width: 600
[[165 354 290 534]
 [ 90 474 154 553]
 [178  43 226 117]]
[ True  True False]
Valid_rects
 [[165 354 290 534]
 [ 90 474 154 553]]
FPS: 9.736963188403779
odict_keys(['obj_503', 'obj_504'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.548937709768806
odict_keys(['obj_503'])
height: 337, width: 600
tracked_box
FPS: 20.463712962827437
odict_keys(['obj_503'])
height: 337, width: 600
tracked_box
FPS: 21.334635496144376
odict_keys([])
height: 337, width: 600
[[ 97 480 162 560]
 [174 326 307 517]
 [172  46 221 123]]
[ True  True False]
Valid_rects
 [[ 97 480 162 560]
 [174 326 307 517]]
FPS: 11.662604237050136
odict_keys(['obj_505', 'obj_506'])
height

tracked_box
FPS: 17.590753151762723
odict_keys(['obj_522'])
height: 337, width: 600
tracked_box
FPS: 18.03908615469309
odict_keys(['obj_522'])
height: 337, width: 600
FPS: 24.470423504839474
odict_keys([])
height: 337, width: 600
[[228 123 333 276]
 [181  24 241 119]]
[ True False]
Valid_rects
 [[228 123 333 276]]
FPS: 12.22786374820706
odict_keys(['obj_523'])
height: 337, width: 600
FPS: 22.790547552937724
odict_keys([])
height: 337, width: 600
FPS: 24.457153519615616
odict_keys([])
height: 337, width: 600
FPS: 22.601786888249432
odict_keys([])
height: 337, width: 600
[[230  91 331 245]
 [178  31 238 114]]
[False False]
Valid_rects
 []
FPS: 13.368853530186112
odict_keys([])
height: 337, width: 600
FPS: 22.801202494142462
odict_keys([])
height: 337, width: 600
FPS: 20.904729389600227
odict_keys([])
height: 337, width: 600
FPS: 23.892361150669323
odict_keys([])
height: 337, width: 600
[[228  64 321 216]]
[False]
Valid_rects
 []
FPS: 13.550207082813742
odict_keys([])
height: 337, width: 

height: 337, width: 600
[[137 463 236 589]
 [168  90 213 171]
 [203 459 291 593]]
[ True False  True]
Valid_rects
 [[137 463 236 589]
 [203 459 291 593]]
FPS: 9.921147496002497
odict_keys(['obj_546', 'obj_547'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.437228368427448
odict_keys(['obj_546', 'obj_547'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 13.369023978988503
odict_keys(['obj_546', 'obj_547'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.12218814078067
odict_keys([])
height: 337, width: 600
[[143 441 255 585]
 [218 426 313 589]
 [165  95 212 180]]
[ True  True False]
Valid_rects
 [[143 441 255 585]
 [218 426 313 589]]
FPS: 8.873340864760115
odict_keys(['obj_548', 'obj_549'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 11.39384983157666
odict_keys(['obj_548', 'obj_549'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 15.666522239321091
odict_keys(['obj_548', 'obj_549'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.1718705

height: 337, width: 600
tracked_box
FPS: 16.039526114922484
odict_keys([])
height: 337, width: 600
[[ 88 391 227 520]
 [195 372 299 533]
 [248   8 307 123]
 [175   0 263 116]]
[ True  True False False]
Valid_rects
 [[ 88 391 227 520]
 [195 372 299 533]]
FPS: 10.02685587379604
odict_keys(['obj_587', 'obj_588'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.965653567019432
odict_keys(['obj_588'])
height: 337, width: 600
tracked_box
FPS: 16.436970706377977
odict_keys(['obj_588'])
height: 337, width: 600
tracked_box
FPS: 17.13793526138156
odict_keys([])
height: 337, width: 600
[[203 342 308 516]
 [ 95 362 237 495]
 [172   0 251 102]
 [235   0 298 106]]
[ True  True False False]
Valid_rects
 [[203 342 308 516]
 [ 95 362 237 495]]
FPS: 10.898655566122553
odict_keys(['obj_589', 'obj_590'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 16.171995249772515
odict_keys(['obj_589'])
height: 337, width: 600
tracked_box
FPS: 18.567986931634564
odict_keys(['obj_589'])
height: 337, wid

height: 337, width: 600
[[109  28 197 109]
 [191  23 243 123]]
[False False]
Valid_rects
 []
FPS: 12.854725163583984
odict_keys([])
height: 337, width: 600
FPS: 20.065271990546947
odict_keys([])
height: 337, width: 600
FPS: 18.917206013016475
odict_keys([])
height: 337, width: 600
FPS: 18.378417222054257
odict_keys([])
height: 337, width: 600
[[189  26 238 123]
 [107  32 194 110]]
[False False]
Valid_rects
 []
FPS: 12.227935045625491
odict_keys([])
height: 337, width: 600
FPS: 22.788318709081526
odict_keys([])
height: 337, width: 600
FPS: 21.797764254049756
odict_keys([])
height: 337, width: 600
FPS: 19.293825411355577
odict_keys([])
height: 337, width: 600
[[107  34 191 111]
 [188  26 234 127]]
[False False]
Valid_rects
 []
FPS: 11.795901263594255
odict_keys([])
height: 337, width: 600
FPS: 23.317752229313527
odict_keys([])
height: 337, width: 600
FPS: 23.317881862404448
odict_keys([])
height: 337, width: 600
FPS: 23.33409735744089
odict_keys([])
height: 337, width: 600
[[185  36 231 

height: 337, width: 600
tracked_box
FPS: 15.915427435236797
odict_keys([])
height: 337, width: 600
FPS: 22.281327858140806
odict_keys([])
height: 337, width: 600
FPS: 23.890728061881273
odict_keys([])
height: 337, width: 600
[[137 373 229 485]]
[ True]
Valid_rects
 [[137 373 229 485]]
FPS: 12.378639687870757
odict_keys(['obj_608'])
height: 337, width: 600
tracked_box
FPS: 20.901812455461037
odict_keys(['obj_608'])
height: 337, width: 600
tracked_box
FPS: 20.47410169921751
odict_keys(['obj_608'])
height: 337, width: 600
tracked_box
FPS: 20.066807962988655
odict_keys([])
height: 337, width: 600
[[145 358 237 478]]
[ True]
Valid_rects
 [[145 358 237 478]]
FPS: 12.228077642956682
odict_keys(['obj_609'])
height: 337, width: 600
tracked_box
FPS: 20.463213769954333
odict_keys(['obj_609'])
height: 337, width: 600
tracked_box
FPS: 21.349404458922937
odict_keys(['obj_609'])
height: 337, width: 600
tracked_box
FPS: 17.903565086736783
odict_keys([])
height: 337, width: 600
[[153 340 247 466]]
[ Tr

height: 337, width: 600
[[179  83 224 175]]
[False]
Valid_rects
 []
FPS: 13.554586056011221
odict_keys([])
height: 337, width: 600
FPS: 23.31853004948018
odict_keys([])
height: 337, width: 600
FPS: 25.084950120810507
odict_keys([])
height: 337, width: 600
FPS: 24.474278778825507
odict_keys([])
height: 337, width: 600
[[176  85 222 176]]
[False]
Valid_rects
 []
FPS: 13.55541838090098
odict_keys([])
height: 337, width: 600
FPS: 23.73673040899599
odict_keys([])
height: 337, width: 600
FPS: 23.318011496936744
odict_keys([])
height: 337, width: 600
FPS: 22.80504567203132
odict_keys([])
height: 337, width: 600
[[173  92 220 177]]
[False]
Valid_rects
 []
FPS: 13.92586690040772
odict_keys([])
height: 337, width: 600
FPS: 25.0675591680612
odict_keys([])
height: 337, width: 600
FPS: 23.891816762933342
odict_keys([])
height: 337, width: 600
FPS: 23.33240989525097
odict_keys([])
height: 337, width: 600
[[168  99 217 175]]
[False]
Valid_rects
 []
FPS: 12.532843291052247
odict_keys([])
height: 337, 

[[ 83 426 130 533]
 [ 18 456 111 564]]
[ True  True]
Valid_rects
 [[ 83 426 130 533]
 [ 18 456 111 564]]
FPS: 11.796199840253793
odict_keys(['obj_617', 'obj_618'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 17.59060560308673
odict_keys([])
height: 337, width: 600
FPS: 22.787947277488616
odict_keys([])
height: 337, width: 600
FPS: 24.4554423117289
odict_keys([])
height: 337, width: 600
[[ 90 430 141 547]
 [ 22 459 118 571]]
[ True  True]
Valid_rects
 [[ 90 430 141 547]
 [ 22 459 118 571]]
FPS: 10.902139981233251
odict_keys(['obj_619', 'obj_620'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 18.23103136518534
odict_keys([])
height: 337, width: 600
FPS: 23.87318644665919
odict_keys([])
height: 337, width: 600
FPS: 23.87345821309245
odict_keys([])
height: 337, width: 600
[[ 95 431 149 535]
 [ 24 466 133 581]]
[ True  True]
Valid_rects
 [[ 95 431 149 535]
 [ 24 466 133 581]]
FPS: 9.734658116385022
odict_keys(['obj_621', 'obj_622'])
height: 337, width: 600
tracked_box
track

FPS: 9.198378009706502
odict_keys(['obj_663', 'obj_664', 'obj_665', 'obj_666'])
height: 337, width: 600
tracked_box
tracked_box
tracked_box
tracked_box
FPS: 12.378895424508672
odict_keys(['obj_663', 'obj_665'])
height: 337, width: 600
tracked_box
tracked_box
{'ep_green': 15, 'ep_black': 20}
FPS: 7.833290378488214
odict_keys(['obj_663', 'obj_665'])
height: 337, width: 600
tracked_box
tracked_box
FPS: 14.538214639759863
odict_keys(['obj_663', 'obj_665'])
height: 337, width: 600
[[245 237 337 486]
 [129 427 222 553]
 [ 91 204 315 334]
 [ 97 478 173 600]
 [152 556 211 599]
 [106 456 193 583]]
[ True  True  True  True  True  True]
Valid_rects
 [[245 237 337 486]
 [129 427 222 553]
 [ 91 204 315 334]
 [ 97 478 173 600]
 [152 556 211 599]
 [106 456 193 583]]
FPS: 8.499440706816893
odict_keys(['obj_663', 'obj_665', 'obj_667', 'obj_668', 'obj_669', 'obj_670'])
height: 337, width: 600
tracked_box
tracked_box
tracked_box
tracked_box
tracked_box
tracked_box
FPS: 7.772584076437842
odict_keys(['obj_